### ISSUE TITLE
"Releasing" instructions leave you with some local changes

### ISSUE THREAD

**Issue by Reinmar** [cksource/mgit2#109]
After executing instructions from https://github.com/cksource/mgit2#releasing-package you end up with a repo which has one commit to be pushed. Either the instructions should be fixed or the `release:publish` task.

**Comment by Reinmar** [comment]
Actually... they don't release anything. I've executed `release:publish` twice now and the package is not published:

```
(master 44e72d4) p@m /workspace/misc/mgit2> npm run release:publish

> mgit2@0.11.0 release:publish /workspace/misc/mgit2
> node ./scripts/publish.js


📍  Configuring the release...
? Select services where packages will be released: (Press <space> to select, <a> to toggle all, <i> to invert selection)npm, GitHub
? Provide the GitHub token: [hidden]
{ Deprecation: [@octokit/rest] octokit.authenticate() is deprecated. Use "auth" constructor option instead.
    at authenticate (/workspace/misc/mgit2/node_modules/@octokit/rest/plugins/authentication-deprecated/authenticate.js:9:44)
    at saveReleaseOptions (/workspace/misc/mgit2/node_modules/@ckeditor/ckeditor5-dev-env/lib/release-tools/tasks/releasesubrepositories.js:201:11)
    at configureRelease.then._releaseOptions (/workspace/misc/mgit2/node_modules/@ckeditor/ckeditor5-dev-env/lib/release-tools/tasks/releasesubrepositories.js:133:29)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'Deprecation' }

📍  Checking whether you are logged to npm...
🔑 Logged as "ckeditor".

📍  Preparing packages that will be released...

📍  Collecting the latest versions of packages published on NPM...

Checking "mgit2"...
✅  Added to release.

📍  Collecting the latest releases published on GitHub...

Checking "mgit2"...
(master 44e72d4) p@m /workspace/misc/mgit2>
```

It should publish 0.11.0 but it didn't.

**Comment by pomek** [comment]
Because of https://github.com/ckeditor/ckeditor5/issues/1889 it didn't work.

**Comment by Reinmar** [comment]
Better, but still warning:

![image](https://user-images.githubusercontent.com/156149/61277767-1f711500-a7b3-11e9-9f31-474586771852.png)
